### ISSUE TITLE
Support for default limit

### ISSUE THREAD

**Issue by laurentS** [laurentS/slowapi#1]
There should be a way to declare a default set of limits that apply to all endpoints without explicitly marking each endpoint with the decorator.

**Comment by Rested** [comment]
ran into this, was there a reason not to implement as a starlette `BaseHTTPMiddleware`? it seems like you started doing that here https://github.com/laurentS/slowapi/blob/4c4141a7dbecf03cd03e0a4529bcf9ba42de687b/slowapi/extension.py#L114 happy to have a crack at implementing that and the exempt decorator

**Comment by laurentS** [comment]
Hi Reuben,

Indeed I had tried at the start, to replicate the functionally of `flask-limiter`, but I couldn't get it to work the way I wanted. I forget the details, but I think it was something along the lines of Starlette's API not allowing the pattern I had in mind. It has probably changed by now, so feel free to implement, I'd be super grateful for a PR!

**Comment by laurentS** [comment]
Closing this as default limit is now available via the middleware, thank @Rested !
