### ISSUE TITLE
Can slowapi be used in production?

### ISSUE THREAD

**Issue by krissik** [laurentS/slowapi#105]
The documention says:
`
Note: this is alpha quality code still, the API may change, and things may fall apart while you try it.
`

Because of that I am unsure if it can be used in production.

**Comment by laurentS** [comment]
@krissik I use it on a small scale production deployment (single server, low traffic). I think some other contributors to this repo use the package in production, but I'll let them confirm.

We should update this statement which is a couple of years old. I think the main change I can foresee in the API is the switch to full async support.
Unless you are using this for very big scale deployments, it should work well enough.
