### ISSUE TITLE
@limiter.limit("1/second") not working

### ISSUE THREAD

**Issue by moo611** [laurentS/slowapi#107]
it worked based on minute, but not working based on second

**Comment by moo611** [comment]
this is my code
`
@app.get("/test")
@limiter.limit("1/second")
async def test(request: Request):
    time.sleep(2)
    return "hello"
`

**Comment by nocturn9x** [comment]
why would you use `time.sleep()` in an async function?! It seems you need to learn how to use Python before using this library...

**Comment by laurentS** [comment]
Let's try and be kind to each other.

@moo611 can you explain a bit more what you are trying to do? As @nocturn9x  pointed out, your example is a bit confusing.
Can you also clarify what you mean by "it's not working". Do you get a specific error?

**Comment by moo611** [comment]
Ok, it's my mistake.Just as @nocturn9x say, I should not use time.sleep in an async function.

**Comment by laurentS** [comment]
Glad you found your problem. Can we close this issue?
