### ISSUE TITLE
Redis backend configuration

### ISSUE THREAD

**Issue by nocturn9x** [laurentS/slowapi#11]
By reading the source code I figured out that it's possible to setup a redis server to be used as a temporary storage for rate limiting data, but I couldn't figure out how to actually use it with slowapi, is there anything I need to configure/import?

**Comment by laurentS** [comment]
Yes, you can. Take a look at [this other issue](https://github.com/laurentS/slowapi/issues/2#issuecomment-618554972) which gives an example. The url for redis should use this format: `redis://hostname:port`.

I'll add an example to the readme (and the docs ;) )

**Comment by nocturn9x** [comment]
Marvelous, thanks!
