### ISSUE TITLE
how to control limit by duration?

### ISSUE THREAD

**Issue by moo611** [laurentS/slowapi#111]
I want to set min duration between each requests. For example I want at least 30s duration between each request.How can I achieve it?

**Comment by nootr** [comment]
Sounds like you want to set a limit of `1/30seconds` with a `moving-window` strategy:

```python
limiter = Limiter(..., strategy="moving-window")

@limiter.limit("1/30seconds")
async def foo(request: Request)
    pass
```

Note that I haven't tested this code, there could be bugs. Let me know if this works for you.

For more info, check `limits`'s docs on [rate-limit-string-notation](https://limits.readthedocs.io/en/latest/quickstart.html?highlight=strategy#rate-limit-string-notation).

@laurentS Maybe there should be docs to describe the different supported strategies?

**Comment by laurentS** [comment]
The different strategies are [documented](https://limits.readthedocs.io/en/latest/strategies.html) in `limit`s docs. Do you think we should duplicate this, or just point to it?

**Comment by moo611** [comment]
okay, I got it. Thanks for all. And I think it is better to write down some strategies for beginners.

**Comment by nootr** [comment]
The strategies are documented, but I was thinking about the string values of the strategies (`fixed-window`, `fixed-window-elastic-expiry`, `moving-window`). These aren't mentioned in the `limits` docs, except in the [source code](https://limits.readthedocs.io/en/latest/_modules/limits/strategies.html).

Maybe we could cross-reference to `limits.strategies.STRATEGIES` in the docstrings?
