### ISSUE TITLE
Global limit? 

### ISSUE THREAD

**Issue by nocturn9x** [laurentS/slowapi#12]
Is it possible to define a "global" limit (still per-user) to apply to all handlers and then have more restrictive limits on a per-handler basis? If so, how?

**Comment by laurentS** [comment]
Yes, you can, look at [this PR](https://github.com/laurentS/slowapi/pull/7). I still have to merge it and do a new release, but it should help in the meantime.

**Comment by laurentS** [comment]
I've been slow at getting this new release out, but hopefully 0.1.2 does what you need? Let me know if not!

**Comment by laurentS** [comment]
Closing as this was fixed in 0.1.2 with the middleware. See https://slowapi.readthedocs.io/en/latest/examples/#apply-a-global-default-limit-to-all-routes for an example
