### ISSUE TITLE
New release/tag 

### ISSUE THREAD

**Issue by edgorman** [laurentS/slowapi#122]
Hey @laurentS 

Just wondering if you're thinking of creating a new release/tag soon with the latest changes, I'm keen to use the custom cost per hit function for the limiter in a project of mine, but [v0.1.6](https://github.com/laurentS/slowapi/releases/tag/v0.1.6) was created a few days before the [PR for the change](https://github.com/laurentS/slowapi/pull/110) was merged.

Great project by the way, it works very well!

Thanks

**Comment by thentgesMindee** [comment]
Hi ! a new release should come in a few days depending on Laurent’s availability: #120

**Comment by edgorman** [comment]
Perfect, thanks for that I'll close this ticket then
