### ISSUE TITLE
RateLimitExceeded is not imported in the example of README

### ISSUE THREAD

**Issue by hruday95** [laurentS/slowapi#16]
RateLimitExceeded is not imported in the example given in README and is causing error during run time.

Add it to the imports : 
from slowapi.errors import RateLimitExceeded

**Comment by laurentS** [comment]
Thanks for reporting this @hruday95, I think the error you're referring to was fixed in #4 
If you use the code in the `master` branch instead of the current release 0.1.1, you should see the corrected examples.
Next release will definitely include the fix!

**Comment by hruday95** [comment]
@laurentS  also same is with the case of pypi documentation.

https://pypi.org/project/slowapi/

Have to fix it there as well.

**Comment by laurentS** [comment]
Good call! I've updated the README and the docs with that in mind, hopefully it is all correct now. Please let me know if you spot any other mistake. Thanks again for pointing it out!
