### ISSUE TITLE
add multiple limiters on a single route.

### ISSUE THREAD

**Issue by RohitPShetty** [laurentS/slowapi#169]
I was trying to add multiple limiters on a single route.

The 1st limiter will utilise a client-id extracted from the request and will impose a restriction of 3 requests per minute on the client while accessing the "/query" endpoint.

The 2nd limiter will be a global limiter which imposes restriction of 5 requests per minute irrespective of the client while accessing the "/query" endpoint.

The ideal behaviour should be that when i try hitting the endpoint "/query" with 5 requests each from 2 different clients, then 3 requests from one client and 2 requests from anotther client should be accepted. However, in reality 3 requests from each client are accepted. Which means that the global limit is not working.

**To Reproduce**

```
client_id_limiter = Limiter(
    key_func=lambda request: request.headers.get("client-uuid"),
)


global_limiter = Limiter(
    key_func=lambda request: request.url.path
)

app.state.limiter = client_id_limiter
app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)

@router.post(
    "/query")
@client_id_limiter.limit("3/minute")
@global_limiter.limit("5/minute")
async def user_query(
    request: Request
) 
```

**Expected behavior**
The ideal behaviour should be that when i try hitting the endpoint "/query" with 5 requests each from 2 different clients, then 3 requests from one client and 2 requests from anotther client should be accepted. However, in reality 3 requests from each client are accepted. Which means that the global limit is not working.

**Your app (please complete the following information):**
 - fastapi
 - Version - fastapi==0.99.1
- slowapi version (have you tried with the latest version)? slowapi==0.1.8

**Additional context**

**Comment by laurentS** [comment]
Hi @RohitPShetty, I don't have time to dig into this right now, but have you tried looking into the storage backend to see what keys are in there? It might give you some hints as to what is going wrong. You could also log what goes into `hit` here: https://github.com/laurentS/slowapi/blob/90ec3ab2f75e45e7eb7cb4a0bf148773955acbfd/slowapi/extension.py#L505

What storage backend do you use?

**Comment by RohitPShetty** [comment]
Hi @laurentS , I currently do not use any explicit storage back-end. I read that slow api uses in memory storage by default. is that true or do I need to explicilty use a storage backend?

**Comment by laurentS** [comment]
You can absolutely use memory storage, but you need to be aware of the limitations:
- if you have multiple `fastapi` processes (often the case in production), then each one will use a separate store, which could lead to the problem you're seeing.
- the data stored will only live as long as the memory storage process, so when you restart your server, limits will be reset, which could be a problem depending on your use case.

If the above are not acceptable for your needs, you probably want to switch to something like redis instead.

**Comment by RohitPShetty** [comment]
oh ok. Thanks for the insight @laurentS. So, in cases wherein multiple container instances of my service(internally using FastAPI) are spawned, then these limits based on client_id will depend on which container the requests reach?

Also, just curious, how do i write a limiter using SlowAPI which imposes a blanket limit of 50 requests per minute to an endpoint like "/query". Unclear on what the "key_func" should return as I'am not really imposing limits based on a key such as Remote address or client id or any other key.

global_limiter = Limiter(key_func=lambda ?????)

**Comment by thentgesMindee** [comment]
@RohitPShetty 

> oh ok. Thanks for the insight @laurentS. So, in cases wherein multiple container instances of my service(internally using FastAPI) are spawned, then these limits based on client_id will depend on which container the requests reach?

Exactly, if you want to share those limits you have to use some kind of persistent storage such as Redis for example.

> Also, just curious, how do i write a limiter using SlowAPI which imposes a blanket limit of 50 requests per minute to an endpoint like "/query". Unclear on what the "key_func" should return as I'am not really imposing limits based on a key such as Remote address or client id or any other key.
>
> global_limiter = Limiter(key_func=lambda ?????)

Returning any string from key_func would work, as long as key_func return the exact same string for each call

**Comment by RohitPShetty** [comment]
@thentgesMindee Thank you for the explanation.

Going back to my original question, how can we achieve something like this?

Adding multiple limiters on a single endpoint "/query".

The 1st limiter will utilise a client-id extracted from the request and will impose a restriction of 3 requests per minute on the client while accessing the "/query" endpoint.

The 2nd limiter will be a global limiter which imposes restriction of 5 requests per minute irrespective of the client while accessing the "/query" endpoint.

The ideal behaviour should be that when i try hitting the endpoint "/query" with 5 requests each from 2 different clients, then 3 requests from one client and 2 requests from another client should be accepted. However, in reality 3 requests from each client are accepted. Which means that the global limit is not working.

**Comment by thentgesMindee** [comment]
> The ideal behaviour should be that when i try hitting the endpoint "/query" with 5 requests each from 2 different clients, then 3 requests from one client and 2 requests from another client should be accepted. However, in reality 3 requests from each client are accepted. Which means that the global limit is not working.

It should work already
You should try again with a single worker of your app running since you're using an in-memory storage

**Comment by RohitPShetty** [comment]
yes, i have verified that I have used a single worker of my app. But still the global limit doesn't work

**Comment by thentgesMindee** [comment]
can you paste the code you use for testing ?

**Comment by RohitPShetty** [comment]
Using a simple curl command with an for loop across 2 terminals with slight difference in client_id to simulate 2 clients:

for i in {1..7}; do                                                              
    curl -X POST \
         -H "Authorization: Bearer your_access_token" \
         -H "client-uuid: 3fa85f64-5717-4562-b3fc-2c963f66afa6" \
         -H "Content-Type: application/json" \
         -d '{"query": "Valid user query"}' \
         http://localhost:8000/user-query &
done

**Comment by laurentS** [comment]
@RohitPShetty I suspect your code has a small bug which we missed:
```python
client_id_limiter = Limiter(
key_func=lambda request: request.headers.get("client-uuid"),
)

global_limiter = Limiter(
key_func=lambda request: request.url.path
)

# global_limiter is never attached to the app
app.state.limiter = client_id_limiter
# instead use a single `Limiter`
app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)

@router.post(
"/query")
@client_id_limiter.limit("3/minute")
@global_limiter.limit("5/minute")
async def user_query(
request: Request
)
```

The tests actually have an example of exactly what you want to do: https://github.com/laurentS/slowapi/blob/90ec3ab2f75e45e7eb7cb4a0bf148773955acbfd/tests/test_fastapi_extension.py#L72

```python
limiter  = Limiter()

@router.post("/query")
@limiter.limit("3/minute", key_func=lambda request: request.headers.get("client-uuid"))
@limiter.limit("5/minute", key_func="shared_by_everyone")
async def user_query(
request: Request
)
```

**Comment by thentgesMindee** [comment]
Good catch @laurentS 
Another option, if you really need both limiter defined differently (for example if you want different storage configuration) could be to make use the global_limiter without any decorator, using its default limit

**Comment by RohitPShetty** [comment]
@laurentS Thanks for looking into this. Have a doubt on the `limited` creation in above code you have posted.

`limiter  = Limiter()`

I keep getting the "key_func" missing in init error for this.

**Comment by laurentS** [comment]
@RohitPShetty this is a python error, not something specific to slowapi. Python is telling you that an argument (`key_func`) is missing in your call to `Limiter()`. You can just add one here, which will act as the default value for `key_func`. If you keep your code as we discussed it above, specifying `key_func` for each `.limit()` then the default value does not really matter, you can pass anything.

You could use the default value for your shared "global limiter" and do something like:

```python
limiter = Limiter(key_func=lambda: "shared_by_everyone")

@router.post("/query")
@limiter.limit("3/minute", key_func=lambda request: request.headers.get("client-uuid"))
@limiter.limit("5/minute") # omit key_func here and the default will be used
async def user_query(
request: Request
)
```

Closing this issue as resolved now.

**Comment by amacfie-tc** [comment]
So maybe the `key_func` argument in `Limiter()` should be called `default_key_func`?
