### ISSUE TITLE
Limit Http Headers

### ISSUE THREAD

**Issue by moayyadfaris** [laurentS/slowapi#18]
I'm setting a rate limit for a route as below

`from slowapi import Limiter, _rate_limit_exceeded_handler`
`from slowapi.util import get_remote_address`
`limiter = Limiter(key_func=get_remote_address, headers_enabled=True)`

`@router.post("/send-verification-otp", response_model=schemas.Msg)`
`@limiter.limit("1/1 minute")`
`def send_verification_otp(`

Check the below error:

AttributeError: 'dict' object has no attribute 'headers'

**Comment by laurentS** [comment]
@moayyadfaris could you share the full stack trace, to help understand what the error is?

**Comment by moayyadfaris** [comment]
Code snippet: 

![alt text](https://i.imgur.com/T5uuzV2.png)

Below is the error stack:

![alt text](https://i.imgur.com/7J20nSa.png)

**Comment by moayyadfaris** [comment]
@laurentS Any update 😇

**Comment by laurentS** [comment]
I haven't had time to check yet. My gut feeling would be to check your versions of starlette/fastapi vs the ones i have in the `project.toml` for slowapi, and see if the data type for `response` has changed in any way. If not, I'll have to check in more detail.

**Comment by glinmac** [comment]
@laurentS @moayyadfaris I faced the same issue with the decorator when the endpoint doesn't return an instance of `Response`. This is a valid FastAPI construct and it lets FastAPI do the transformation into a `response_model` or as needed later in the middleware stack.

@moayyadfaris did it happen in this context?

Hopefully, I think that #19 should address it.
