### ISSUE TITLE
dynamic_limit isn't really dynamic

### ISSUE THREAD

**Issue by yanqianglu** [laurentS/slowapi#206]
**Describe the bug**

I would expect the callable `limit_value: StrOrCallableStr` to be executed for every request, because I use something like configcat or LaunchDarkly to dynamically update the rate limit as needed, like below

```
@limiter.limit(
    get_rate_limit(feature_flag="api1_rate_limit", default_value="10/minute"),
)

...

def get_rate_limit(
    feature_flag: str,
    default_value: str,
    configcat: ConfigCatClient = get_configcat(),
) -> str:
    return configcat.get_value(flag, default_value)
```

However, I found the `limit_value` seems to be cached by some key (I guess it's the key from key_func), so it only be called once and the new value from configcat is not being picked up.

**To Reproduce**
See description above.

**Expected behavior**
If limit_value is a callable, can we make a flag somewhere to make sure it's being called for every request?

**Screenshots**
N/A

**Your app (please complete the following information):**
 - fastapi
 - 0.109.1
- slowapi version: 0.1.9

**Additional context**
N/A

**Comment by laurentS** [comment]
I suspect your code is not doing what you think it should do. If you are indeed using what you wrote above, then you are actually calling `get_rate_limit` at start time only, because you are passing `@limiter.limit` the result of that initial call, not the callable itself.

If you want to call `get_rate_limit` on each call with default arguments to the function, you need to create a function that you can pass to the `limit` constructor, something like:
```python
def get_limit():
    return get_rate_limit(feature_flag="api1_rate_limit", default_value="10/minute")

@limiter.limit(
    get_limit,
)
...
```

Let me know if this helps.

**Comment by yanqianglu** [comment]
> I suspect your code is not doing what you think it should do. If you are indeed using what you wrote above, then you are actually calling `get_rate_limit` at start time only, because you are passing `@limiter.limit` the result of that initial call, not the callable itself.
> 
> If you want to call `get_rate_limit` on each call with default arguments to the function, you need to create a function that you can pass to the `limit` constructor, something like:
> 
> ```python
> def get_limit():
>     return get_rate_limit(feature_flag="api1_rate_limit", default_value="10/minute")
> 
> @limiter.limit(
>     get_limit,
> )
> ...
> ```
> 
> Let me know if this helps.

oh, you're right. I mis-used that. Thanks for the explanation!
