### ISSUE TITLE
Using slowapi in bigger application

### ISSUE THREAD

**Issue by himalacharya** [laurentS/slowapi#25]
In test.py from app is run:
```
import uvicorn

from app.main import app

if __name__ == "__main__":
    uvicorn.run("test:app", host="0.0.0.0", port=8000, reload=True)

```
In main.py
```
from app.api.api_v1.api import router as api_router
from fastapi import FastAPI
from slowapi import Limiter, _rate_limit_exceeded_handler
from slowapi.util import get_remote_address
from slowapi.errors import RateLimitExceeded
def get_application() -> FastAPI:
     application = FastAPI(title=PROJECT_NAME, debug=DEBUG, version=VERSION)
     application.add_event_handler(
        "startup", create_start_app_handler(application))
     application.add_event_handler(
        "shutdown", create_stop_app_handler(application))
    application.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)
    application.include_router(api_router, prefix=API_PREFIX)

     return application
app = get_application()
```

In endpoint user.py, how to use   @limiter.limit("5/minute") ? 
```
from starlette.requests import Request
router = APIRouter()
@router.post('/show',
             tags=["show"],
             name="show:show")
async def homepage(request: Request):
        return PlainTextResponse("test")
***code****
```
In this use case how to use slowapi in endpoint. I need to **limit to 5 requests per minute per user only and block that user for a minute** Sleep and retry after a minute

In api.py
```
from app.api.api_v1.endpoints.show import router as ShowRouter

router = APIRouter()



router.include_router(ShowRouter, tags=["show"], prefix="/show")

**Comment by laurentS** [comment]
Hi @himalacharya is your question about how to import `limiter` in your endpoint file? Or about limiting per user? In that latter case, you need to define what "user" means. Is it an IP address? their userID? something else?

**Comment by himalacharya** [comment]
> Hi @himalacharya is your question about how to import `limiter` in your endpoint file? Or about limiting per user? In that latter case, you need to define what "user" means. Is it an IP address? their userID? something else?

My question is to how to import limiter in endpoint and limiting per user. user is just endpoint name :
http://0.0.0.0:8000/api/v1/user/user

**Comment by laurentS** [comment]
For the import, you could simply instantiate the `Limiter` in a separate file, say `limiter.py` and then import it in your `main.py` and also in the files where you define your routes.
To limit users, as I mentioned above, you need to decide what a user means. Look at https://slowapi.readthedocs.io/en/latest/ and the FastAPI example, you'll see that the constructor takes a `key_func` argument. Whatever this function returns identifies a "user".

**Comment by himalacharya** [comment]
> For the import, you could simply instantiate the `Limiter` in a separate file, say `limiter.py` and then import it in your `main.py` and also in the files where you define your routes.
> To limit users, as I mentioned above, you need to decide what a user means. Look at https://slowapi.readthedocs.io/en/latest/ and the FastAPI example, you'll see that the constructor takes a `key_func` argument. Whatever this function returns identifies a "user".

I will solve accordingly but @limiter.limit("5/minute") shows "limiter" has no attribute 'limit' error

**Comment by himalacharya** [comment]
> For the import, you could simply instantiate the `Limiter` in a separate file, say `limiter.py` and then import it in your `main.py` and also in the files where you define your routes.
> To limit users, as I mentioned above, you need to decide what a user means. Look at https://slowapi.readthedocs.io/en/latest/ and the FastAPI example, you'll see that the constructor takes a `key_func` argument. Whatever this function returns identifies a "user".

I wrote accordingly but found such error.
```
Traceback (most recent call last):
  File "C:\Users\Himal\anaconda3\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 388, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\Himal\anaconda3\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\Himal\anaconda3\lib\site-packages\fastapi\applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\Himal\anaconda3\lib\site-packages\starlette\applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Himal\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc from None
  File "C:\Users\Himal\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\Himal\anaconda3\lib\site-packages\starlette\middleware\base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "C:\Users\Himal\anaconda3\lib\site-packages\slowapi\middleware.py", line 33, in dispatch
    if name in limiter._exempt_routes:
AttributeError: 'function' object has no attribute '_exempt_routes'

```
In limiter.py
```
from slowapi import Limiter, _rate_limit_exceeded_handler
from slowapi.util import get_remote_address
from slowapi.errors import RateLimitExceeded


def limiter():
    limiter = Limiter(key_func=get_remote_address, default_limits=["1/minute"])
   
   
    return limiter
```

In main.py
```
    application.state.limiter = limiter
    application.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)
    application.add_middleware(SlowAPIMiddleware)
    ```

**Comment by laurentS** [comment]
Your code is not importing the `limiter` object but a function, that's why it's not working. You don't need that extra limiter function, you can just define the object in the limiter file and import it elsewhere.

**Comment by himalacharya** [comment]
> Your code is not importing the `limiter` object but a function, that's why it's not working. You don't need that extra limiter function, you can just define the object in the limiter file and import it elsewhere.

I am stuck whole day and couldn't troubleshoot. Could you help  writing limiter file code?

**Comment by himalacharya** [comment]
Thank you very much

**Comment by shaythuram** [comment]
> Hi @himalacharya is your question about how to import `limiter` in your endpoint file? Or about limiting per user? In that latter case, you need to define what "user" means. Is it an IP address? their userID? something else?

How would i do for IP ?
