### ISSUE TITLE
Global default limit in FastAPI

### ISSUE THREAD

**Issue by papapumpnz** [laurentS/slowapi#26]
Setting up the default global limit for all routes using this:

```
    # global rate limiter
    limiter = Limiter(key_func=default_identifier,
        default_limits=["1/minute"],
        headers_enabled=True,
        storage_uri="redis://XXXXXX.home",
        in_memory_fallback_enabled=True)
    app.state.limiter = limiter
    app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)
```

But all routes are not getting rate limited. If I add the limiter decorator to a route and test it works as expected. What am I missing here?

I am adding routes using separate modules and attaching to app as so :
`app.include_router(data.router)`

**Comment by laurentS** [comment]
I think you forgot to add the middleware that enables the default/global limit.
```python
from slowapi.middleware import SlowAPIMiddleware
# ... your code above...
app.add_middleware(SlowAPIMiddleware)
```

I was about to point you to the relevant example in the docs, but I realise I've managed to make it incorrect, my apologies! I'll fix it after dinner :)
Please let me know if the above works for you.

**Comment by papapumpnz** [comment]
Yep that did the trick. Working now as expected. Thanks for that, wouldn't have thought to add it as a middleware.
