### ISSUE TITLE
FastAPI 'RateLimitExceeded' is not defined

### ISSUE THREAD

**Issue by vbrinza** [laurentS/slowapi#32]
I am trying the FastAPI example and I get :
```
  File "./basic.py", line 13, in <module>
    app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)
NameError: name 'RateLimitExceeded' is not defined
```
Python 3.9
fastapi 0.63.0
slowapi 0.1.3

**Comment by himalacharya** [comment]
Most of these things are missing in example. I have used this to import RateLimitExceeded
from slowapi.errors import RateLimitExceeded

**Comment by laurentS** [comment]
Thanks for pointing out the error, and sorry about the trouble, I need to find a better way to write these examples, so they remain valid as they get updated. I've updated the docs.
