### ISSUE TITLE
Cache backend documentation

### ISSUE THREAD

**Issue by Maracko** [laurentS/slowapi#40]
I cannot find the documentation on how to set up the different types of backend's (Redis,Memcache) anywhere in the docs.

Could you please add it to the documentation or point me in the right direction?

**Comment by laurentS** [comment]
The docs do need a lot of work, don't they?

I'll eventually get to it, but here's how you can setup a redis backend:
```python
limiter = Limiter(key_func=get_remote_address, storage_uri="redis://<host>:<port>/n")
```
where the `/n` in the redis url is the database number. To use the default one, just drop the `/n` from the url.

There are more examples in the [limits docs](https://limits.readthedocs.io/en/stable/storage.html) which is the library slowapi uses to manage storage.

Feel free to send a short PR with doc updates if you want :)

**Comment by laurentS** [comment]
I've just added an example in the [docs](https://slowapi.readthedocs.io/en/latest/examples/)
