### ISSUE TITLE
Access Limiter within route files

### ISSUE THREAD

**Issue by quiktea** [laurentS/slowapi#44]
I would like to access my limiter object which is in my `app.py` file, within one of my route files which are within my `routes` directory. Can anyone help me do this?

Current Code:
```py
from slowapi import Limiter, _rate_limit_exceeded_handler
from slowapi.util import get_remote_address
from slowapi.errors import RateLimitExceeded

limiter = Limiter(key_func = get_remote_address)
app.state.limiter = limiter
app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)
```

**Comment by quiktea** [comment]
Never Mind, I have figured this out now. Thank you for making slowapi!

**Comment by pranithan-kang** [comment]
Cloud you please share how you can pass it to the router? I am facing this problem too.
