### ISSUE TITLE
Is it possible to conditionally rate limit depending on HTTP header information?

### ISSUE THREAD

**Issue by danieljfarrell** [laurentS/slowapi#5]
Thanks for this project and a great name!

An example of conditional rate limiting: rate limit a REST endpoint to 1 call per minute *per user*. The user can be identified by a token in the HTTP header. I appreciate adding predicates other than time can make this messy fast! At the same time, I'm sure this is an extremely common problem. I guess people resort to solving this in there apps because the problem is so domain specific.

**Comment by laurentS** [comment]
Hi @danieljfarrell, thanks for your interest!
You can rate limit based on the request header quite easily. Essentially you decide how to identify your "user" with the `identify_my_user_func` in the example below (I've copied this from the example code in the README):

```python
    limiter = Limiter(key_func=identify_my_user_func)
    app = Starlette()
    app.state.limiter = limiter
```

That function gets passed the incoming `Request` object, and returns a string which determines which user's limits the request is counted against. In your case, if your users have a token, you could do something like:
```python
def get_user_from_headers(request: Request):
    user = identify_user_from_token(request.headers['token'])
    return user.username
```

Does this help?

**Comment by danieljfarrell** [comment]
That’s brilliant! It’s hard to make this so extendable in an elegant way. I will give it a go.
