### ISSUE TITLE
rate limit issue

### ISSUE THREAD

**Issue by swicaksono** [laurentS/slowapi#6]
Hi, thank you for making this great tools.
I have an issue when I set a rate limit to "1/second". After initiation the service and try to call the api, in the first second I always get error of too many requests.

there is the limiter class:
```
limiter = Limiter(key_func=get_remote_address)
```

I've used this decorator:
```
@limiter.limit("1/second")
```
And the app setup:
```
app.state.limiter = limiter
app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)
```
Any help? Thanks.

**Comment by laurentS** [comment]
Hi @swicaksono, thanks for your kind words!
Have you configured a backend, or are you using the default in-memory one? Are you seeing the HTTP 429 status code from the very first request? The `get_remote_address` function that comes with `slowapi` is very basic, and often returns the wrong IP address for the requester. See #2 for some ideas.
Do you still have the problem if you raise the limit to something higher, like "10/second"?

**Comment by laurentS** [comment]
@swicaksono are you still having issues with this? If not, can you close the issue?

**Comment by himalacharya** [comment]
Can we ratelimit to 10 per every 15 seconds?

In Issue  #25 , I solved the problem but  I didn't use request:Request in endpoint. It worked without request:request.

**Comment by laurentS** [comment]
I'm going to close this as inactive for a while. Please reopen and comment if still relevant
