### ISSUE TITLE
TypeError: __init__() got multiple values for argument 'key_func'

### ISSUE THREAD

**Issue by XPr0methiumX** [laurentS/slowapi#67]
The code :- 
from fastapi import FastAPI, Request
from slowapi import Limiter, _rate_limit_exceeded_handler
from slowapi.util import get_remote_address
from slowapi.errors import RateLimitExceeded
from threading import Thread
from lyrics_extractor import SongLyrics
from helpers.meme import get_meme

app = FastAPI(title="General API V2", description = "An API for everything!")
limiter = Limiter(app, key_func=get_remote_address)
app.state.limiter = limiter
app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)

The error :- 
TypeError: __init__() got multiple values for argument 'key_func'

This is incredibly weird and seems to be a problem from the package itself and not from my code, probably a problem with the Limiter class but I can be wrong.. I'm using the version 0.1.5 of the slowapi, any help is appreciated, Thanks!

**Comment by Rested** [comment]
You're gonna want to initialize like this:
```python
limiter = Limiter(key_func=get_remote_address)
app = FastAPI()
app.state.limiter = limiter
app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)
```

It doesn't take `app` as the first argument. See https://slowapi.readthedocs.io/en/latest/
