### ISSUE TITLE
rate limited for route

### ISSUE THREAD

**Issue by ducthanh200398** [laurentS/slowapi#8]
![image](https://user-images.githubusercontent.com/64213702/90092451-2ae69500-dd53-11ea-87b0-3ac558e564e5.png)
in flask-limiter we can use limiter.exempt(...) for blueprint or bluprint route. can i do any thing like that at the moment

**Comment by laurentS** [comment]
Hi @ducthanh200398, thanks for your interest!
As far as I know, FastAPI doesn't have anythling like blueprints, but once I merge #7 you should be able to use the `exempt()` decorator. Note however that right now, there is no default limit, so you can positively mark the routes you want limited with the decorator, and just not decorate the routes you don't want limited.
After the PR is merged, this will still work, or you'll be able to add the middleware as a default limit, and use `exempt()`.
I will update this ticket once this is merged.

**Comment by ducthanh200398** [comment]
@laurentS  fastapi have APIRouter work like blueprint in flask, limiter decorator not working vs APIRouter

**Comment by laurentS** [comment]
Just a heads up that #7 is now merged, and released in `0.1.2`. Hope that it works for you!

**Comment by laurentS** [comment]
I think the middleware (see https://slowapi.readthedocs.io/en/latest/examples/) does what you describe here. If not, feel free to reopen and clarify what you need.
