### ISSUE TITLE
$.ajax and $.getJSON request not limited

### ISSUE THREAD

**Issue by Matt0550** [laurentS/slowapi#85]
Hi everyone, I'm having a problem. When I make too many browser or postman requests rightly the APIs block me as I set, but if I make a request via AJAX and jquery's $ .getJSON, I'm not limited. How can I solve?

**Comment by laurentS** [comment]
Hi @Matt0550 can you copy the exact content of the requests being made in both cases? And your setup of slowapi? It's a bit difficult to help you with no info about your config.

**Comment by Matt0550** [comment]
> Hi @Matt0550 can you copy the exact content of the requests being made in both cases? And your setup of slowapi? It's a bit difficult to help you with no info about your config.

With Stackoverflow I fixed https://stackoverflow.com/questions/71164792/fastapi-and-slowapi-not-working-on-ajax-and-getjson-request-python
