### ISSUE TITLE
Redis Version Conflict: install failed when redis > 4.0

### ISSUE THREAD

**Issue by a-yangyi** [laurentS/slowapi#88]
The conflict is caused by:
    The user requested redis==4.2.0rc3
    slowapi 0.1.5 depends on redis<4.0.0 and >=3.4.1

**Comment by salsudeer** [comment]
Any update on this?

**Comment by xbogdan** [comment]
This is still causing issues, maybe remove the redis version requirement? I see that the limits package supports redis >3 and <5. Is it necessary to have it in the pyproject.toml though?

**Comment by twcurrie** [comment]
Sorry, this was resolved with the PR #96, but a new release wasn't published.  We'll follow up with that and publish the latest as a release.

**Comment by laurentS** [comment]
Hi all, sorry for the lag. I am still the only person who can push a release. I will try to make one in the next few days, and find a way to make the release process go through github actions, so that any maintainer of the repo can create one going forward.

**Comment by twcurrie** [comment]
@laurentS I have the start of a branch to do so, but at a minimum, you'll need to put some pypi credentials as a repo secret.

**Comment by laurentS** [comment]
@twcurrie brilliant! Feel free to open a PR whenever you're happy with your code. I'd really like to make it so that there is no single bottleneck in the maintenance of this repo (particularly me!).

**Comment by salsudeer** [comment]
> Hi all, sorry for the lag. I am still the only person who can push a release. I will try to make one in the next few days, and find a way to make the release process go through github actions, so that any maintainer of the repo can create one going forward.

Waiting for it 🙏

**Comment by twcurrie** [comment]
Due to personal reasons, I won't have any github action based release process PR ready soon.  @laurentS will need to manually issue the release.
