### ISSUE TITLE
Documentation? 

### ISSUE THREAD

**Issue by nocturn9x** [laurentS/slowapi#9]
Hi, I was looking for a way to rate limit my production FastAPI backend and I stumbled upon this repo, which seems to meet my needs, but lacks documentation. I was able to grasp some stuff from the examples and by reading the source code, but is there any chance to find proper documentation for this project?

Best Regards, and thanks for making this!

**Comment by laurentS** [comment]
Hi @nocturn9x, thanks for your interest. You're right, there is no proper documentation yet. I'm doing this on my spare time, and there hasn't been enough of it for docs :)
What do you think would be most important to have first? examples? API reference? something else?

**Comment by nocturn9x** [comment]
First of all, thanks for the time you're dedicating to this project, and to reply to my issues as well :). I think that an API reference would be extremely useful, at least in my opinion, because it would cover the entire codebase. Also, I see you use standard compliant docstrings so using a tool such as sphinx and hosting the documentation on readthedocs shouldn't be too much of a hassle. Examples can, and should, be added later when a proper reference is in place

**Comment by laurentS** [comment]
Cool, thanks for the feedback! I wasn't aiming to do much more complex stuff than readthedocs or equivalent ;) I'll update this issue when it's available.

**Comment by nocturn9x** [comment]
I'll take advantage of this open issue to ask another question as well, tell me if I should open another issue instead. But is there any way to return a completely custom JSON response after the rate limit being hit? I have an `APIResponse` object which is  subclass of `pydantic.BaseModel` and would like to return a custom JSON to stay consistent with the rest of my API :)

**Comment by laurentS** [comment]
Can you open a separate ticket for this? I don't have an immediate answer for you, but I think there should be a way to do it. Can you include an example of what you'd like as a JSON response?

**Comment by nocturn9x** [comment]
@laurentS sure, done!

**Comment by laurentS** [comment]
I've setup minimal docs at https://slowapi.readthedocs.io/en/latest/ Will keep them growing, but thought I'd mention it already!

**Comment by laurentS** [comment]
Closing this as the docs are now at https://slowapi.readthedocs.io/en/latest/
If you need more additions, please open new issues, and we can look into them.
