### ISSUE TITLE
Feature request: Add support for the `cost` keyword parameter from Limits 

### ISSUE THREAD

**Issue by VMAtm** [laurentS/slowapi#94]
In the 2.3 version of the limits the custom `cost` parameter was introduced:
https://github.com/alisaifee/limits/releases/tag/2.3.0

Could you please update the code so it can be adjustable? E.g., it can be useful to throttle requests based on content-length header, and not just a request counts

**Comment by laurentS** [comment]
Hi @VMAtm thanks for raising this. I don't have bandwidth to work on this at the moment. You're welcome to submit a PR with the needed changes though!
