### ISSUE TITLE
places to ask for help?

### ISSUE THREAD

**Issue by ResetXD** [laurentS/slowapi#95]
Is there a discord server or gitter where someone could ask questions?
i think GitHub issues page isn't the best place to ask small library related questions.

**Comment by laurentS** [comment]
We don't have a gitter or discord, but I've just setup [discussions](https://github.com/laurentS/slowapi/discussions) for this repo, which indeed would be a better place to ask questions than the issues tracker.

Closing this now, but you're welcome to ask your question over there!
